package com.nanzhufeng.nanfengbazi

import org.junit.Assert.assertEquals
import org.junit.Test

class CaseWorkflowAutoNameTest {
    @Test
    fun `自动姓名从最小未占用序号开始且不复用回收站名称`() {
        assertEquals(
            "某某3",
            nextAutoGeneratedCaseAlias(listOf("某某", "某某1", "某某2", "普通案例")),
        )
        assertEquals("某某1", nextAutoGeneratedCaseAlias(emptyList()))
        assertEquals("某某2", nextAutoGeneratedCaseAlias(listOf("某某1", "某某3")))
    }

    @Test
    fun `自动姓名同样避开列表显示姓名`() {
        assertEquals("某某3", nextAutoGeneratedCaseAlias(listOf("内部别名", "某某1", "某某2")))
    }
}
